config/routes.rb
Rails.application.routes.draw do
  root 'human_people#index'
  resources :human_people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/human_person.rb
class HumanPerson < ApplicationRecord

validates_presence_of :name, :age, :hair_color, :eye_color, :gender, :alive



def info
 "person =  #{name}, #{age}, #{hair_color}, #{eye_color}, #{gender} #{alive}"
end



def self.by_name
 order(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/human_people_controller.rb
class HumanPeopleController < ApplicationController
  def index
    @people = HumanPerson.all
  end

  def show

       @person = HumanPerson.find(params[:id]) 
  end

  def new
    @person = HumanPerson.new
  end


  def create
    @person = HumanPerson.new(person_params)
    if @person.save
      redirect_to human_person_path(@person)
    else
      render :new
    end
  end

  def edit
      @person = HumanPerson.find(params[:id])
    end

    def update
    @person = HumanPerson.find(params[:id])
    if @person.update(person_params)
      redirect_to human_person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = HumanPerson.find(params[:id])
    @person.destroy
    redirect_to human_person_path
  end


  private
  def person_params
    params.require(:human_person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/human_person_helper.rb
module HumanPersonHelper
end

app/views/human_people/_form.html.erb
<%= form_for @person do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>
  <div>
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
  </div>


  <div>
   <%= f.label :eye_color %>
   <%= f.text_field :eye_color %>
 </div>

  <div>
   <%= f.label :gender %>
   <%= f.text_field :gender %>
 </div>

  <div>
   <%= f.label :alive %>
   <%= f.select :alive, [['yes', true ], ['no', false]] %>
  </div>

<%= f.submit %>


<% end %>

app/views/human_people/edit.html.erb
<h1> Edditing <%= @person.name %> </h1>

<%= render(partial: 'form') %>

<%= link_to 'back', human_person_path %>

app/views/human_people/index.html.erb
<h1>all people</h1>

<% if @people.any? %>
  <%   @people.each do |person| %>
  <div>
    <%= link_to person.info, human_person_path(person) %>
  </div>
  <% end %>

  <% else %>
  <h3>No people found, Please create one!</h3>
<% end %>

<%= link_to 'New person', new_human_person_path %>

app/views/human_people/new.html.erb
<h1>create A new person</h1>

<%= render(partial: 'form') %>

app/views/human_people/show.html.erb
<h1> <%= @person.name %>  </h1>

<ul>
 <li>age: <%= @person.age %></li>
 <li>hair_color: <%= @person.hair_color %></li>
 <li>eye_color: <%= @person.eye_color %></li>
 <li>gender: <%= @person.gender %></li>
 <li>alive: <%= @person.alive %></li>
 <li>
   <%= link_to 'Edit',  edit_human_person_path(@person) %>
  <%= link_to 'Delete', human_person_path(@person), method: :delete %>
 </li>
</ul>

<%= link_to 'All people', human_people_path %>

app/views/human_person/show.html.erb
<h1> <%= @person.name %>  </h1>

<ul>
 <li>age: <%= @person.age %></li>
 <li>hair_color: <%= @person.hair_color %></li>
 <li>eye_color: <%= @person.eye_color %></li>
 <li>gender: <%= @person.gender %></li>
 <li>alive: <%= @person.alive %></li>
 <li>
   <%= link_to 'Edit',  edit_human_person_path(@person) %>
  <%= link_to 'Delete', human_person_path(@person), method: :delete %>
 </li>
</ul>

<%= link_to 'All people', human_person_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Person</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>